In [11]:
import numpy as np
import pandas as pd

In [27]:
a=np.arange(0,5)
a #numpy_array

array([0, 1, 2, 3, 4])

In [26]:
a_new=pd.DataFrame({'A_column':a})
a_new #pandas_dataframe

A_column
0         0
1         1
2         2
3         3
4         4

In [5]:
b=np.arange(5,10)
b #numpy_array

array([5, 6, 7, 8, 9])

In [28]:
b_new=pd.DataFrame({'B_column':b})
b_new #pandas_dataframe

B_column
0         5
1         6
2         7
3         8
4         9

In [6]:
a+b #array addition

array([ 5,  7,  9, 11, 13])

In [29]:
a*b #array mulitplication

array([ 0,  6, 14, 24, 36])

In [47]:

print(var1)
print('------')
print(type(b))

<class 'numpy.ndarray'>
------
<class 'numpy.ndarray'>


In [48]:
a_new.info()
print('----------')
b_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
A_column    5 non-null int32
dtypes: int32(1)
memory usage: 148.0 bytes
----------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
B_column    5 non-null int32
dtypes: int32(1)
memory usage: 148.0 bytes


In [34]:
np.dot(a_new,b_new.T) #dot product of dataframe( transpose is required)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

In [49]:
np.dot(a,b) #dot product of arrays

80

In [65]:
a_m=np.array([[1, 2], [4, 5],[3,6]])
a_m

array([[1, 2],
       [4, 5],
       [3, 6]])

In [66]:
type(a_m)
# a_m[1]

numpy.ndarray

In [67]:
a_m_new=pd.DataFrame({'c1':a_m[:,0],'c2':a_m[:,1]})

In [68]:
a_m_new

c1  c2
0   1   2
1   4   5
2   3   6

In [70]:
a_m_new.shape

(3, 2)

In [72]:
b_m=np.array(np.identity(3))
b_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])